window.$ = window.jQuery = require('jquery');

import '../adminlte/plugins/datatables/jquery.dataTables.min.js';
import '../adminlte/plugins/datatables-bs4/js/datatables.js';
import './bootstrap';
import '../adminlte/plugins/jquery/jquery.min.js';
import '../adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js';
import '../adminlte/dist/js/adminlte.min.js';
import './components/teacher.js';
import './components/sidebar.js';
import './curso/components/navbar.js';
import './curso/components/footer.js';
import './curso/detalle-curso.js';
import './curso/video.js';
import './curso/cuestionario.js';
import './curso/dian-components/new-dian.js';
import './curso/dian-components/formulario-dian.js';
import './curso/dian-components/create-form-dian.js';
import './curso/dian-components/formulario-110-dian.js';
import './curso/dian-components/left-panel.js';
import './rutas/view-rutas.js';
import './rutas/list-rutas.js';
//import '../adminlte/';